# destination: Redux-Framework
# markdown: redcarpet

base_dir: /Redux-Framework

project: Redux Theme Options Framework
github: https://github.com/ghost1227/Redux-Framework
download: https://github.com/ghost1227/Redux-Framework/archive/master.zip
changelog: https://github.com/ghost1227/Redux-Framework/commits/master
issues: https://github.com/ghost1227/Redux-Framework/issues

topbar:
  -
    url : '/index.html'
    title : 'Home'
  -
    url : '/docs.html'
    title : 'Documentation'
  -
    url : '/about.html'
    title : 'About'
  -
    url : '/news.html'
    title : 'News'
  -
    url : '/tags.html'
    title : 'Tags'
  -
    url : '/categories.html'
    title : 'Categories'

